// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // schema.prisma itself now reads DATABASE_URL too (env("DATABASE_URL")), so this normally
    // just mirrors whatever's already set in .env.local. The "file:./dev.db" fallback only
    // matters if DATABASE_URL is somehow unset when a Prisma CLI command runs (db push/studio) —
    // satisfies the type here rather than crashing outright in that edge case.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
