// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Matches prisma/schema.prisma's own hardcoded datasource url exactly — that's what the
    // generated client actually uses at runtime; DATABASE_URL isn't referenced there at all, so
    // this fallback is only to satisfy the type here for Prisma CLI commands (db push/studio).
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
