// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Bare `dotenv/config` only auto-loads a file literally named `.env` — this project has always
// used `.env.local` (Next.js's own dev-env convention, loaded automatically by `next dev` and
// passed explicitly to the collab sidecar via `tsx --env-file=.env.local`), so the Prisma CLI
// never actually saw DATABASE_URL without this. Explicit path fixes `prisma db push`/`generate`/
// `studio` failing with "Environment variable not found: DATABASE_URL" even though the running
// app itself works fine.
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // schema.prisma itself now reads DATABASE_URL too (env("DATABASE_URL")), so this normally
    // just mirrors whatever's already set in .env.local. The "file:./dev.db" fallback only
    // matters if DATABASE_URL is somehow unset when a Prisma CLI command runs (db push/studio) —
    // satisfies the type here rather than crashing outright in that edge case.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
