// Generates the Android splash screen and the web boot screen's mark from ONE piece of artwork.
//
// They used to draw the letter separately — the splash through next/og, which renders with its own
// bundled font, and the boot screen with the device's sans-serif. Those are different typefaces, so
// the mark visibly changed shape at the handover between them ("det er ikke en gang samme S?").
// Drawing it twice could never be made to match; sharing one image cannot fail to.
//
// Run with: node scripts/generate-splash.mjs
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const SRC = 'android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png';
const RES = 'android/app/src/main/res';

// A typical modern phone aspect. The splash is drawn CENTER_CROP, which scales by whichever axis
// needs more — so on a screen of roughly this shape the scale is governed by width, and anything
// sized as a share of this image's width lands on the same share of the screen. That is what keeps
// the mark the same size as the boot screen's, which is sized in `vw`.
const W = 1080;
const H = 2400;

// These three numbers are the contract with app/page.tsx's boot screen. Change them together.
const MARK_WIDTH_SHARE = 0.23; // the S, as a share of screen width
const RING_BOX_SHARE = 0.58; // the ring's bounding box, same share the boot screen uses
const RING_RADIUS_IN_BOX = 0.47;
const RING_STROKE_IN_BOX = 0.02;
const RING_LIT = 77 / 295; // the fraction of the circle that is lit, matching the boot screen

const ringBox = W * RING_BOX_SHARE;
const r = ringBox * RING_RADIUS_IN_BOX;
const stroke = ringBox * RING_STROKE_IN_BOX;
const circumference = 2 * Math.PI * r;
const arc = circumference * RING_LIT;

const trimmed = await sharp(SRC).trim().png().toBuffer();
const meta = await sharp(trimmed).metadata();

const markWidth = Math.round(W * MARK_WIDTH_SHARE);
const markHeight = Math.round(markWidth * (meta.height / meta.width));
const mark = await sharp(trimmed).resize(markWidth, markHeight).png().toBuffer();

// The ring is drawn on the splash too, stationary. Without it the boot screen appeared to add a
// circle out of nowhere; with it, the only thing that changes at the handover is that the ring
// starts moving. The user's suggestion, and the right one.
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <rect width="${W}" height="${H}" fill="#0a0a0a"/>
  <g transform="translate(${W / 2} ${H / 2})">
    <circle r="${r}" fill="none" stroke="#60a5fa" stroke-opacity="0.14" stroke-width="${stroke}"/>
    <circle r="${r}" fill="none" stroke="#60a5fa" stroke-width="${stroke}" stroke-linecap="round"
            stroke-dasharray="${arc.toFixed(1)} ${(circumference - arc).toFixed(1)}"/>
  </g>
</svg>`;

const composed = await sharp(Buffer.from(svg))
  .composite([{ input: mark, gravity: 'centre' }])
  .png({ compressionLevel: 9 })
  .toBuffer();

// One splash for every configuration. @capacitor/assets generated 26 density and orientation
// variants; they exist to avoid upscaling a small asset, and this one is larger than any phone
// screen and CENTER_CROPped regardless, so a single drawable is both simpler and sharper.
for (const entry of fs.readdirSync(RES, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const p = path.join(RES, entry.name, 'splash.png');
  if (fs.existsSync(p)) fs.unlinkSync(p);
}
fs.mkdirSync(path.join(RES, 'drawable'), { recursive: true });
fs.writeFileSync(path.join(RES, 'drawable', 'splash.png'), composed);

// The same artwork for the web boot screen, inlined so it costs no request on the one path where
// the network is the entire problem. Palette-quantised: the mark is a single flat colour, so 16
// entries is indistinguishable from full colour at a twentieth of the bytes.
const web = await sharp(trimmed)
  .resize({ height: 300 })
  .png({ palette: true, colours: 16, compressionLevel: 9, effort: 10 })
  .toBuffer();

fs.writeFileSync(
  'lib/bootMark.ts',
  [
    '// GENERATED by scripts/generate-splash.mjs — do not edit by hand.',
    '//',
    '// The Siqt mark, shared by the native splash screen and the web boot screen so the two cannot',
    '// disagree about its shape. A data URI rather than a file: the boot screen must not need a',
    '// network request on the one path where the network is the whole problem.',
    '',
    `export const BOOT_MARK_SRC = '${'data:image/png;base64,' + web.toString('base64')}';`,
    '',
    '// Width / height, so callers can size it before the image has loaded.',
    `export const BOOT_MARK_ASPECT = ${(meta.width / meta.height).toFixed(4)};`,
    '',
    '// Shares of screen width, matching the constants in this file’s generator. The boot screen',
    '// uses them as vw so it lands on the same proportions the splash was drawn at.',
    `export const BOOT_MARK_WIDTH_SHARE = ${MARK_WIDTH_SHARE};`,
    `export const BOOT_RING_BOX_SHARE = ${RING_BOX_SHARE};`,
    '',
  ].join('\n')
);

console.log(`splash: ${W}x${H}, ${Math.round(composed.length / 1024)} KB`);
console.log(`boot mark: ${Math.round((web.length / 1024) * 10) / 10} KB`);
